version: "3.8"

services:

  config-server:
    image: "vermau2k01053/config-server:v2"
    container_name: "config-server"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - QBank

  accounts:
    image: "vermau2k01053/accounts:v2"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - QBank
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      config-server:
        condition: service_healthy

  loans:
    image: "vermau2k01053/loans:v2"
    container_name: "loans-ms"
    ports:
      - "8086:8086"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - QBank
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      config-server:
        condition: service_healthy

  cards:
    image: "vermau2k01053/cards:v2"
    container_name: "cards-ms"
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - QBank
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      config-server:
        condition: service_healthy

networks:
  QBank:
    driver: "bridge"
