spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Utkarshkverma/configuration-ms.git"
          default-label: main
          timeout: 5
          clone-on-start: true
#        native:
#          search-locations: "classpath:/config"

server:
  port: 8071
encrypt:
  key: "QWERTYMNBVCXZUIOPASDFGLKJHG102939495867"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true